### ISSUE TITLE
XML Entities not handled correctly

### ISSUE THREAD

**Issue by UlrichLohrmann** [weblegacy/struts1#11]
We have <html:submit> fields that have XML Entities for German Umlaut in the value of the value attribute, for example

<html:submit property="..." value="Zur&uuml;ck"/>

The &uuml; XML Entity should display German Umlaut ü on the page but instead the XML text is "Zur%uuml;ck" without replacing the XML Entity &uuml; with German Umlaut ü.

The reason is that during rendering of the value of the value property the TagUtils.getInstance().filter(..) method is called which calls ResponseUtils.filter(). In ResponseUtils.filter() the input string is examined and if a '&' is found it is prepended with &amp;. So in my case the input value of ResponseUtils.filter is "Zur&uuml;ck" and the return is "Zur&aml;&uuml;ck" and as a result the &uuml; XML Entity is not replaced with the German Umlaut.

From my point of view, the ResponseUtils.filter class should have a list of valid XML entities that are accepted and not escaped, so that the result string does not contain the XML Entity but the expected text.

**Comment by ste-gr** [comment]
Hallo Ulrich,

in the next Version (end of July I think) we would adapt the `ResponseUtils.filter` in such a way that the following string-parts
- `& [a-zA-Z][0-9a-zA-Z]* ;`
- `&# [0-9]+ ;`
- `&#x [0-9a-fA-F]+ ;`

are also not filtered.

For example, the values `Zur&uuml;ck` or `Footnote &sup1;` are then taken over unchanged.

Greetings
Stefan

**Comment by ste-gr** [comment]
Hi @UlrichLohrmann,

I have released the new version [1.4.5](../releases/tag/v1.4.5), in which your problem is solved. I have also added a new sample page ([apps/examples/src/main/webapp/exercise/html-button.jsp](../blob/STRUTS_1_4_X/apps/examples/src/main/webapp/exercise/html-button.jsp)) to test this issue.

Greetings
Stefan
