### ISSUE TITLE
Consider change in major release number when using JakartaEE 9

### ISSUE THREAD

**Issue by UlrichLohrmann** [weblegacy/struts1#13]
The next release will be with jakartaEE as documented on the project's landing page. The version of the next release is also documented to be 1.4.5.

Wouldn't it be better to increase the major version number than the patch level number as the change to JakartaEE seems to be a breaking change and with Semantic Versioning a breaking change should increase the major number? Otherwise, dynamic versions in build files (for example 1.4.+ in a Gradle build file) would use the JakartaEE version as soon as published in a Maven repo. In addition, security fixes for the JavaEE version would be difficult if the JakartaEE version would be 1.4.5, as no free patch level number would then be free after 1.4.4

**Comment by ste-gr** [comment]
Hi @UlrichLohrmann,

your are right.
I'll reserve the version-range 1.4.X for the `struts1`-version JEE8 (javax-namespace) and 1.5 for JEE9+ (jakarta-namespace).

If you also need to run `struts1` under the jakarta-namespace, I have good news for you. The version 1.5.0-SNAPSHOT is  **ready for Jakarta-Namespace**!

What is needed for the local-version:

1. [tiles-request-jakarta-servlet](/weblegacy/tiles-request-jakarta-servlet)
    `mvn clean install`
2. [struts1](/weblegacy/struts1)
    `mvn -Pdormant clean install`

Now I will work on to release `struts1` and `tiles-request-jakarta-servlet`. But in the meantime you could test this version with your applications.

Good luck with testing,
Greetings
Stefan

**Comment by ste-gr** [comment]
Hi @UlrichLohrmann,

I'll follow your suggestion:
* JEE8 --> 1.4.X
* JEE9 --> 1.5.X
* JEE10 --> 1.6.X

and so on.

The version for JEE9 (1.5.0-RC1) is already out!

Greetings
Stefan
