### ISSUE TITLE
IOException in commons-fileupload2 method

### ISSUE THREAD

**Issue by lukamalovic** [weblegacy/struts1#17]
In the commons-fileupload2 dependency, the getString(Charset cs) method in FileItem now throws an IOException, which it did not previously. I was able to mitigate this in the weblegacy-chain branch by propagating the error anywhere the method was referenced, although I imagine going forward a more robust solution would be preferred, which is why I'm making note of it here.

**Comment by ste-gr** [comment]
Hello @lukamalovic,

I have solved the problem with c0532cd. There were also some other changes for fileupload2.
I think it is not necessary to route the IOException. But have a look at my changes.

Greetings
Stefan
