### ISSUE TITLE
Are active scans conducted on weblegacy/struts1 to identify new vulnerabilities?

### ISSUE THREAD

**Issue by arjunballa** [weblegacy/struts1#21]
We are considering upgrading our legacy project using `weblegacy/struts1`.
- We are curious if the team responsible for maintaining this project conducts active scans to identify new vulnerabilities.
- Will the maintenance team address and fix any potential vulnerabilities in the future?
- Can widely used market tools like Prisma scans detect vulnerabilities in this project?

**Comment by ste-gr** [comment]
Hello @arjunballa,

it's nice that you want to use `weblegacy/struts1`. I'll try to answer your questions:
* Currently, `GitHub` security scans are being performed. Almost all of `GitHub`'s security tools are enabled.
* When I get know of any vulnerabilities I'll fix it. Of course, any contribution is welcome.
* It think it's possible. Currently the scanning is done with `CodeQL`

Greetings
Stefan

**Comment by ste-gr** [comment]
Hi @arjunballa,

with version 1.5.0-RC2 all currently known security vulnerabilities have been fixed.

Greetings
Stefan
