### ISSUE TITLE
What is still needed for the 1.4.5 release & will there be a 1.4.6 for EE 10?

### ISSUE THREAD

**Issue by jbisotti** [weblegacy/struts1#9]
We have a legacy project that still uses Struts 1.x heavily. Other aspects of the project have been updated and as part of that we want to move from Tomcat 8.5+Spring 5.3.x to Tomcat 10+Spring 6.x but Struts 1.x is holding us back. I just came across this project and am impressed to see all the modernization you've done. What are you plans going forward with this project? If possible, I'd love to use this but EE 10 is what we need.

**Comment by ste-gr** [comment]
Hi! I'm currently working to modernize and update to EE 9 of "[commons-chain](https://github.com/weblegacy/commons-chain/tree/CHAIN_1_X)" and "[tiles-request-servlet](https://github.com/apache/tiles-request/tree/trunk/tiles-request-servlet)". This two dependencies are needed by Struts1.
I think, the upgrade from EE9 to EE10 is then more or less easy.

Currently the roadmap looks like this:
* commons-chain (wip)
   * Upgrade to current maven-plugin-versions (done)
   * Upgrade to JDK-8 (i.e. add generics) (nearly done)
   * Upgrade JUnit3 to JUnit5 (open)
   * Split to sub-projects (open)
   * Add sub-project for EE 9 (open)
   * Change `commons-logging` to `slf4j` (open)
* tiles-request-servlet (open)
   * Copy and upgrade to EE 9
   * Upgrade JUnit4 to JUnit5
* struts1 - EE9 (wip)
   * Upgrade EE 8 to EE 9 (done)
   * Integrate upgraded dependencies `commons-chain` and `tile-request-servlet`
   * Update documentation
* struts1 - EE10 (open)
   * Upgrade EE 9 to EE 10
   * Add `module-info.java`s
   * Update documentation

Of course, help is always welcome.

**Comment by jbisotti** [comment]
If I were to find some time to help, what would you suggest I look into first?

**Comment by ste-gr** [comment]
Hi, sorry for my late reply (vacation). I'll prepare all necessary dependencies and maybe you can extend it with
* set `groupId` to `io.github.weblegacy`
* jakarta-namespace like `commons-fileupload2` with `jaksrvlt` as package-part-name
* at least set `automatic-module-name`

I think this could be a fast way to the new `struts1`-version.

Or maybe you have a better idea, it would be fine to discuss it.

Greetings
Stefan

**Comment by ste-gr** [comment]
Hi @jo-kl,
thank you for helping me. Currently there are 3 blocking dependencies:
* commons-chain
* commons-fileupload
* tiles-request

On `commons-chain` I'm currently working and I think I'm nearly ready.
At `commons-fileupload` and `tiles-request` adaptions for the jakarta-namespace are missing. Maybe you could make work on one (or two ;-)) of them. Please see me change-suggestions above.

Greetings
Stefan

**Comment by jo-kl** [comment]
Hi Stefan,
I have already cloned both repos but have questions regarding your change suggestions.
Maybe we could have a short meeting and discuss the topics? How can we get in contact? I couldn't find your email address...

**Comment by jo-kl** [comment]
Hi @ste-gr,

sorry, but I didn't receive an email. Could you please try this address: betty.klausner@gmail.com

**Comment by lukamalovic** [comment]
Hi Stefan,

I'd also like to contribute towards getting this update completed. What's the status of it, are there any tasks available to work on?

Thanks,
Luka

**Comment by ste-gr** [comment]
Hi Luka,

thank you for your contribution-offer.

Currently it has the following status:
* I have started to change the namespaces from `javax` to `jakarta`.
* Unfortunately, the following dependencies are not yet JEE9+ compatible:
   * [commons-fileupload](https://github.com/apache/commons-fileupload) (there is now version 2, which is JEE9+ compatible) - Open Task: Adapt Struts1 to version 2.0.0-M1.
   * [commons-chain](https://github.com/weblegacy/commons-chain) (I'm working on this right now, very old)
   * [tiles-request-servlet](https://github.com/weblegacy/tiles-request-servlet) (I still want to have a look at the current solution, write a small doc and then publish it) - Open Tasks: Write short doc/README

Nice to have, but not necessary:
* [tlddoc](https://github.com/weblegacy/tlddoc) - Tag Library Documentation Generator
   * Update to taglib 3.0 (from 2.1)
   * [Testcases](https://github.com/weblegacy/tlddoc/issues/1)
* [taglib-maven-plugin](https://github.com/weblegacy/taglib-maven-plugin) - Update to new tlddoc

Greetings
Stefan

**Comment by ste-gr** [comment]
Hi @jbisotti, @lukamalovic, @jo-kl,

:tada: :tada: great news! :tada: :tada:

The Struts1-Version 1.5.0-SNAPSHOT is **ready for Jakarta-Namespace**!

What is needed for the local-version:

1. [tiles-request-jakarta-servlet](/weblegacy/tiles-request-jakarta-servlet)
    `mvn clean install`
2. [struts1](/weblegacy/struts1)
    `mvn -Pdormant clean install`

Now I will work on to release `struts1` and `tiles-request-jakarta-servlet`. But in the meantime you could test this version with your applications.

Good luck with testing,
Greetings
Stefan

**Comment by ste-gr** [comment]
Hi @jbisotti, @lukamalovic, @jo-kl,

the Struts1-Version **ready for Jakarta-Namespace** (JEE9+) has been released (Version 1.5.0-RC1)!

Greetings
Stefan
